import type { Metadata } from "next";
import "../globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ShoppingCart from "./components/shoppingCart/ShoppingCart";
import { Providers } from "../lib/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
          <ShoppingCart />
        </Providers>
      </body>
    </html>
  );
}
